### PR TITLE
London 9 - Mo Mahboobian - JS-Core-1 - Week 1

### PR DESCRIPTION
**Pull request by momahboobian**
**Volunteers: Are you marking this coursework?** _You can find a guide on how to mark this coursework in `HOW_TO_MARK.md` in the root of this repository_

# Your Details

- Your Name: Mo Mahboobian
- Your City: London
- Your Slack Name: Mo Mahboobian

# Homework Details

- Module: JS-Core-1
- Week: Week 1

# Notes

- What did you find easy?
 Syntax Errors
- What did you find hard?
Adding decimals
- What do you still not understand?
None
- Any other notes?

### CODE REVIEW

**Comment by momahboobian** [comment]
Hi @qingwei91,
I have found the problem and I managed to fix it but accidentally I have removed my pull request.
Now I have lost your comments 🤦🏻‍♂️ as well as your reviews ☹️

**Comment by qingwei91** [comment]
@momahboobian oops, did you actually delete the Pull Request?

**Comment by qingwei91** [comment]
Ah ha, I found it here: https://github.com/CodeYourFuture/JavaScript-Core-1-Coursework-Week1/pull/420

**Review by bensonarafat — COMMENTED** [review]
This is Good

**Pull request closed without merging**
