### PR TITLE
WM-4/ JavaScript-Core-1-Coursework-Week1/Mesgna-Woldeab

### PR DESCRIPTION
**Pull request by Mesgna616**
**Volunteers: Are you marking this coursework?** _You can find a guide on how to mark this coursework in `HOW_TO_MARK.md` in the root of this repository_

# Your Details

- Your Name:
- Your City:
- Your Slack Name:

# Homework Details

- Module:
- Week:

# Notes

- What did you find easy?

- What did you find hard?

- What do you still not understand?

- Any other notes?

### CODE REVIEW

**Review by nholdsworth94 — COMMENTED** [review]
Great bit of homework there Mesgna, well done!
Couple of very small insignificant pieces
Great work :)

**Comment by Mesgna616** [comment]
Dear Nick
Thank you for the feedback. I am still working on the extras. I haven't
finished it yet. I am planning to finish it tomorrow.

 Best regards

**Review by Dawit-Dev — COMMENTED** [review]
Mesgna, I like how you approached the problem and your code is easy to read.

**Review by nholdsworth94 — COMMENTED** [review]
extra - 2 task looks great, well done :D

**Pull request closed without merging**
