### PR TITLE
changing var to const

### PR DESCRIPTION
**Pull request by Hamisakim**
Updating vars in this to const :) 

-----
[View rendered exercises/C-variables/README.md](https://github.com/CodeYourFuture/JavaScript-Core-1-Coursework-Week1/blob/sami-updates/exercises/C-variables/README.md)
[View rendered exercises/D-strings/README.md](https://github.com/CodeYourFuture/JavaScript-Core-1-Coursework-Week1/blob/sami-updates/exercises/D-strings/README.md)
[View rendered exercises/E-strings-concatenation/README.md](https://github.com/CodeYourFuture/JavaScript-Core-1-Coursework-Week1/blob/sami-updates/exercises/E-strings-concatenation/README.md)
[View rendered exercises/F-strings-methods/README.md](https://github.com/CodeYourFuture/JavaScript-Core-1-Coursework-Week1/blob/sami-updates/exercises/F-strings-methods/README.md)
[View rendered exercises/G-numbers/README.md](https://github.com/CodeYourFuture/JavaScript-Core-1-Coursework-Week1/blob/sami-updates/exercises/G-numbers/README.md)
[View rendered exercises/I-floats/README.md](https://github.com/CodeYourFuture/JavaScript-Core-1-Coursework-Week1/blob/sami-updates/exercises/I-floats/README.md)
[View rendered exercises/J-functions/README.md](https://github.com/CodeYourFuture/JavaScript-Core-1-Coursework-Week1/blob/sami-updates/exercises/J-functions/README.md)
[View rendered exercises/L-functions-nested/README.md](https://github.com/CodeYourFuture/JavaScript-Core-1-Coursework-Week1/blob/sami-updates/exercises/L-functions-nested/README.md)

### CODE REVIEW

**Comment by SallyMcGrath** [comment]
@Dedekind561 And there's this I've just seen too. 

These PRs will always get missed as there's so much noise on this repos.

**Review by Dedekind561 — APPROVED** [review]
LGTM

**Comment by Dedekind561** [comment]
Oh wait tests are failing :thinking:

**Comment by Dedekind561** [comment]
Just seen your comment in the email notification re failing tests. I do feel a little nauseous myself :vomiting_face:

**Pull request merged**
