### PR TITLE
Palestine Class 1 - Hassan Sammour - Javascript - 1

### PR DESCRIPTION
**Pull request by HassanGhazy**
**Volunteers: Are you marking this coursework?** _You can find a guide on how to mark this coursework in `HOW_TO_MARK.md` in the root of this repository_

# Your Details

- Your Name:
- Your City:
- Your Slack Name:

# Homework Details

- Module:
- Week:

# Notes

- What did you find easy?

- What did you find hard?

- What do you still not understand?

- Any other notes?

### CODE REVIEW

**Comment by Mahmoud-Nwiry** [comment]
Good Job. 👏

**Comment by khaled-Mohamed1** [comment]
well done

**Comment by nidaa-awawdeh** [comment]
`function calculateSalesTax(num) {
    return num * 1.2;
}`

 i think you must explain how you put 1.2 after add 1 to 20% and  you can name the parameter  price  in 4-tax.js file

**Comment by HamedHejjo** [comment]
greet job , 
function calculateSalesTax(num) { return num * 1.2; }

You only calculated the percentage, you have to subtract the percentage from the price

**Pull request closed without merging**
